package smilee.testing.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import smilee.testing.greendao.TeammateData;

import smilee.testing.greendao.TeammateDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig teammateDataDaoConfig;

    private final TeammateDataDao teammateDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        teammateDataDaoConfig = daoConfigMap.get(TeammateDataDao.class).clone();
        teammateDataDaoConfig.initIdentityScope(type);

        teammateDataDao = new TeammateDataDao(teammateDataDaoConfig, this);

        registerDao(TeammateData.class, teammateDataDao);
    }
    
    public void clear() {
        teammateDataDaoConfig.getIdentityScope().clear();
    }

    public TeammateDataDao getTeammateDataDao() {
        return teammateDataDao;
    }

}
