package smilee.testing.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TEAMMATE_DATA.
 */
public class TeammateData {

    private Long id;
    private String Name;
    private String Gender;
    private Integer Age;
    private String Birthday;
    private Integer Seniority;
    private String AddDate;

    public TeammateData() {
    }

    public TeammateData(Long id) {
        this.id = id;
    }

    public TeammateData(Long id, String Name, String Gender, Integer Age, String Birthday, Integer Seniority, String AddDate) {
        this.id = id;
        this.Name = Name;
        this.Gender = Gender;
        this.Age = Age;
        this.Birthday = Birthday;
        this.Seniority = Seniority;
        this.AddDate = AddDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getGender() {
        return Gender;
    }

    public void setGender(String Gender) {
        this.Gender = Gender;
    }

    public Integer getAge() {
        return Age;
    }

    public void setAge(Integer Age) {
        this.Age = Age;
    }

    public String getBirthday() {
        return Birthday;
    }

    public void setBirthday(String Birthday) {
        this.Birthday = Birthday;
    }

    public Integer getSeniority() {
        return Seniority;
    }

    public void setSeniority(Integer Seniority) {
        this.Seniority = Seniority;
    }

    public String getAddDate() {
        return AddDate;
    }

    public void setAddDate(String AddDate) {
        this.AddDate = AddDate;
    }

}
